<?xml version="1.0" encoding="utf-8"?><Database Name="MapEditor" Class="LinqToSQLClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MapEditor;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="CodeMvvm.Properties.Settings" SettingsPropertyName="MapEditorConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tiles" Member="Tiles">
    <Type Name="Tile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PositionX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PositionY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RotationAngle" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TopLeft" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TopMiddle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TopRight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RightMiddle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BottomRight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BottomMiddle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BottomLeft" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LeftMiddle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IsUserOn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>