#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMvvm
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MapEditor")]
	public partial class LinqToSQLClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTile(Tile instance);
    partial void UpdateTile(Tile instance);
    partial void DeleteTile(Tile instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public LinqToSQLClassesDataContext() : 
				base(global::CodeMvvm.Properties.Settings.Default.MapEditorConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSQLClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tile> Tiles
		{
			get
			{
				return this.GetTable<Tile>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tiles")]
	public partial class Tile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _PositionX;
		
		private System.Nullable<int> _PositionY;
		
		private string _Path;
		
		private System.Nullable<double> _RotationAngle;
		
		private System.Nullable<bool> _TopLeft;
		
		private System.Nullable<bool> _TopMiddle;
		
		private System.Nullable<bool> _TopRight;
		
		private System.Nullable<bool> _RightMiddle;
		
		private System.Nullable<bool> _BottomRight;
		
		private System.Nullable<bool> _BottomMiddle;
		
		private System.Nullable<bool> _BottomLeft;
		
		private System.Nullable<bool> _LeftMiddle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPositionXChanging(System.Nullable<int> value);
    partial void OnPositionXChanged();
    partial void OnPositionYChanging(System.Nullable<int> value);
    partial void OnPositionYChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnRotationAngleChanging(System.Nullable<double> value);
    partial void OnRotationAngleChanged();
    partial void OnTopLeftChanging(System.Nullable<bool> value);
    partial void OnTopLeftChanged();
    partial void OnTopMiddleChanging(System.Nullable<bool> value);
    partial void OnTopMiddleChanged();
    partial void OnTopRightChanging(System.Nullable<bool> value);
    partial void OnTopRightChanged();
    partial void OnRightMiddleChanging(System.Nullable<bool> value);
    partial void OnRightMiddleChanged();
    partial void OnBottomRightChanging(System.Nullable<bool> value);
    partial void OnBottomRightChanged();
    partial void OnBottomMiddleChanging(System.Nullable<bool> value);
    partial void OnBottomMiddleChanged();
    partial void OnBottomLeftChanging(System.Nullable<bool> value);
    partial void OnBottomLeftChanged();
    partial void OnLeftMiddleChanging(System.Nullable<bool> value);
    partial void OnLeftMiddleChanged();
    #endregion
		
		public Tile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionX", DbType="Int")]
		public System.Nullable<int> PositionX
		{
			get
			{
				return this._PositionX;
			}
			set
			{
				if ((this._PositionX != value))
				{
					this.OnPositionXChanging(value);
					this.SendPropertyChanging();
					this._PositionX = value;
					this.SendPropertyChanged("PositionX");
					this.OnPositionXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionY", DbType="Int")]
		public System.Nullable<int> PositionY
		{
			get
			{
				return this._PositionY;
			}
			set
			{
				if ((this._PositionY != value))
				{
					this.OnPositionYChanging(value);
					this.SendPropertyChanging();
					this._PositionY = value;
					this.SendPropertyChanged("PositionY");
					this.OnPositionYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="VarChar(MAX)")]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RotationAngle", DbType="Float")]
		public System.Nullable<double> RotationAngle
		{
			get
			{
				return this._RotationAngle;
			}
			set
			{
				if ((this._RotationAngle != value))
				{
					this.OnRotationAngleChanging(value);
					this.SendPropertyChanging();
					this._RotationAngle = value;
					this.SendPropertyChanged("RotationAngle");
					this.OnRotationAngleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopLeft", DbType="Bit")]
		public System.Nullable<bool> TopLeft
		{
			get
			{
				return this._TopLeft;
			}
			set
			{
				if ((this._TopLeft != value))
				{
					this.OnTopLeftChanging(value);
					this.SendPropertyChanging();
					this._TopLeft = value;
					this.SendPropertyChanged("TopLeft");
					this.OnTopLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopMiddle", DbType="Bit")]
		public System.Nullable<bool> TopMiddle
		{
			get
			{
				return this._TopMiddle;
			}
			set
			{
				if ((this._TopMiddle != value))
				{
					this.OnTopMiddleChanging(value);
					this.SendPropertyChanging();
					this._TopMiddle = value;
					this.SendPropertyChanged("TopMiddle");
					this.OnTopMiddleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopRight", DbType="Bit")]
		public System.Nullable<bool> TopRight
		{
			get
			{
				return this._TopRight;
			}
			set
			{
				if ((this._TopRight != value))
				{
					this.OnTopRightChanging(value);
					this.SendPropertyChanging();
					this._TopRight = value;
					this.SendPropertyChanged("TopRight");
					this.OnTopRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightMiddle", DbType="Bit")]
		public System.Nullable<bool> RightMiddle
		{
			get
			{
				return this._RightMiddle;
			}
			set
			{
				if ((this._RightMiddle != value))
				{
					this.OnRightMiddleChanging(value);
					this.SendPropertyChanging();
					this._RightMiddle = value;
					this.SendPropertyChanged("RightMiddle");
					this.OnRightMiddleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottomRight", DbType="Bit")]
		public System.Nullable<bool> BottomRight
		{
			get
			{
				return this._BottomRight;
			}
			set
			{
				if ((this._BottomRight != value))
				{
					this.OnBottomRightChanging(value);
					this.SendPropertyChanging();
					this._BottomRight = value;
					this.SendPropertyChanged("BottomRight");
					this.OnBottomRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottomMiddle", DbType="Bit")]
		public System.Nullable<bool> BottomMiddle
		{
			get
			{
				return this._BottomMiddle;
			}
			set
			{
				if ((this._BottomMiddle != value))
				{
					this.OnBottomMiddleChanging(value);
					this.SendPropertyChanging();
					this._BottomMiddle = value;
					this.SendPropertyChanged("BottomMiddle");
					this.OnBottomMiddleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottomLeft", DbType="Bit")]
		public System.Nullable<bool> BottomLeft
		{
			get
			{
				return this._BottomLeft;
			}
			set
			{
				if ((this._BottomLeft != value))
				{
					this.OnBottomLeftChanging(value);
					this.SendPropertyChanging();
					this._BottomLeft = value;
					this.SendPropertyChanged("BottomLeft");
					this.OnBottomLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftMiddle", DbType="Bit")]
		public System.Nullable<bool> LeftMiddle
		{
			get
			{
				return this._LeftMiddle;
			}
			set
			{
				if ((this._LeftMiddle != value))
				{
					this.OnLeftMiddleChanging(value);
					this.SendPropertyChanging();
					this._LeftMiddle = value;
					this.SendPropertyChanged("LeftMiddle");
					this.OnLeftMiddleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _IsUserOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIsUserOnChanging(int value);
    partial void OnIsUserOnChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUserOn", DbType="Int NOT NULL")]
		public int IsUserOn
		{
			get
			{
				return this._IsUserOn;
			}
			set
			{
				if ((this._IsUserOn != value))
				{
					this.OnIsUserOnChanging(value);
					this.SendPropertyChanging();
					this._IsUserOn = value;
					this.SendPropertyChanged("IsUserOn");
					this.OnIsUserOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
