<?xml version="1.0" encoding="utf-8"?><Database Name="MapEditor" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MapEditor;Integrated Security=True;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="CodeMvvm.Properties.Settings" SettingsPropertyName="MapEditorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tiles" Member="Tiles">
    <Type Name="Tile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="posX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="posY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>